#! /bin/sh

#################
### AUTOSTART ###
#################

# killall any process to be autostarted to avoid duplicate processes
killall "sxhkd"
sxhkd &
killall "picom"
picom -b &
killall "polybar"
$HOME/.config/polybar/launch.sh &
# randomise wallpaper
shuf -e -n1 $HOME/Pictures/Wallpapers/* | xargs feh --bg-scale --no-fehbg

################
### MONITORS ###
################

xrandr --output DP-0 --primary --mode 1920x1080 --rate 170 --rotate normal --output DP-2 --mode 1920x1080 --rate 170 --rotate normal --left-of DP-0

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10


##############
### LAYOUT ###
##############

bspc config window_gap 15

bspc config border_width 5

# monitor padding
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# default split ratio
bspc config split_ratio 0.5

# insertion scheme (longest_side, alternate, spiral)
bspc config automatic_scheme longest_side

# which child to attach a window to when adding a window on a single window tree (first_child, second_child)
bspc config initial_polarity second_child

bspc config center_pseudo_tiled true

# tightness of algorithm to decide if a window is on the (direction) side of another window (high, low)
bspc config directional_focus_tightness high

# adjust brother when unlinking a node from the tree
bspc config removal_adjustment true

# draw preselection area
bspc config presel_feedback true

######################
### MONOCLE LAYOUT ###
######################

bspc config borderless_monocle false

bspc config gapless_monocle false

# auto monocle if only one window
bspc config single monocle false

# monocle padding
bspc config top_monocle_padding 20
bspc config bottom_monocle_padding 20
bspc config left_monocle_padding 20
bspc config right_monocle_padding 20

###############
### POINTER ###
###############

# minimum interval in miliseconds between motion notify events
bspc config pointer_motion_interval 15

# {shift, control, lock, mod1, mod2, mod3, mod4, mod5}
bspc config pointer_modifier mod4

# {move, resize_side, resize_corner, focus, none}
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# {button1, button2, button3, any, none}
bspc config click_to_focus none
# dont replay click that focuses a window
bspc config swallow_first_click false

bspc config focus_follows_pointer true
bspc config focus_follows_monitor true
bspc config pointer_follows_focus true

#############
### THEME ###
#############

# active window on inactive monitor
bspc config active_border_color "#474645"

bspc config focused_border_color "#817f7f"

bspc config normal_border_color "#30302f"

bspc config presel_feedback_color = "#f4d775"

############
### MISC ###
############

# prefix of statusline
bspc config status_prefix = "BSPWM:"

# handle the next x mapping events
bspc config mapping_events_count 0

# path to external rules file. if not used, leave blank
bspc config external_rules_command

bspc config ignore_ewmh_focus false
# {all, none}
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts false
bspc config honor_size_hints true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true 
bspc config merge_overlapping_monitors false
