;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880


[bar/bar1]
inherit = bar/base
monitor = DP-0
; modules
modules-left = bspwm
modules-center = title 
modules-right = network filesystem memory cpu date tray


[bar/bar2]
inherit = bar/base
monitor = DP-2
; modules
modules-left = bspwm
modules-center = title 
modules-right = network filesystem memory cpu date


[bar/base]
; bar positioning
width = 95%
height = 24px
; set x-offset = (100 - width)/2 to have the bar balanced
offset-x = 2.5%
offset-y = 5

; module positioning
padding-left = 2
padding-right = 2
module-margin-left = 1
module-margin-right = 1
fixed-center = false

; theming
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 2
border-color = ${colors.primary}
separator = |
separator-foreground = ${colors.primary}
; rounded corners
radius = 5

; text
font-0 = JetBrainsMono Nerd Font;2
locale = en_GB.UTF-8
; Set a DPI values used when rendering scalable
; Set this to 0 to let polybar calculate the dpi from the screen size.
dpi-x = 0
dpi-y = 0

; misc
wm-restack = bspwm
enable-struts = true
enable-ipc = true
; If two clicks are received within this interval (ms), they are recognized as
; a double click.
double-click-interval = 400
; Possible values are:
; - default   : The default pointer as before, can also be an empty string (default)
; - pointer   : Typically in the form of a hand
; - ns-resize : Up and down arrows, can be used to indicate scrolling
cursor-click = pointer 
cursor-scroll = ns-resize


[module/bspwm]
type = internal/bspwm

; Only show workspaces defined on the same output as the bar
; NOTE: The bspwm and XRandR monitor names must match, which they do by default.
; But if you rename your bspwm monitors with bspc -n this option will no longer
; behave correctly.
pin-workspaces = true

; Output mode flags after focused state label
inline-mode = false

; Create click handler used to focus workspace
enable-click = true

; Create scroll handlers used to cycle workspaces
enable-scroll = true

; Set the scroll cycle direction 
reverse-scroll = false

; Use fuzzy (partial) matching on labels when assigning 
; icons to workspaces
; Example: code;♚ will apply the icon to all workspaces 
; containing 'code' in the label
fuzzy-match = true

; Only scroll through occupied workspaces
occupied-scroll = false

; ws-icon-[0-9]+ = <label>;<icon>
; Note that the <label> needs to correspond with the bspwm workspace name
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 0;10
ws-icon-default =

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(focused|urgent|occupied|empty)>
;   <label-mode> - gets replaced with <label-(monocle|tiled|fullscreen|floating|locked|sticky|private)>
format = <label-state>
label-monitor = %name%

; Available tokens:
;   %name%
;   %icon%
;   %index%
label-focused = %icon%
label-focused-foreground = ${colors.primary}
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-foreground = ${colors.secondary}
label-occupied-background = ${colors.background-alt}
label-occupied-underline = ${colors.secondary}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${colors.secondary}
label-urgent-background = ${colors.alert}
label-urgent-underline = ${colors.alert}
label-urgent-paddinmg = 1

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-background = ${colors.background}
label-empty-underline = ${colors.disabled}
label-empty-padding = 1

; Separator in between workspaces
label-separator = |
label-separator-padding = 0
label-separator-foreground = ${colors.primary}


[module/cpu]
type = internal/cpu
interval = 1
warn-percentage = 95

format =   <label> <ramp-load>
format-foreground = ${colors.primary}
label = %percentage%%
label-foreground = ${colors.foreground}

format-warn =  <label-warn> <ramp-load>
format-warn-foreground = ${colors.primary}
label-warn = CPU WARNING %percentage%%
label-warn-foreground = ${colors.alert}

ramp-load-0 = ▁
ramp-load-1 = ▂
ramp-load-2 = ▃
ramp-load-3 = ▄
ramp-load-4 = ▅
ramp-load-5 = ▆
ramp-load-6 = ▇
ramp-load-7 = █


[module/date]
type = internal/date
interval = 1.0

time = %H:%M:%S
date = %a %d-%b-%Y

format =   <label>
format-background = ${colors.background} 
format-foreground = ${colors.primary}

label = %time% %date%
label-font = 3
label-foreground = ${colors.foreground}


[module/filesystem]
type = internal/fs
mount-0 = /
interval = 30
spacing = 4
warn-percentage = 80

format-mounted = <label-mounted>
format-unmounted =
format-warn = <label-warn>

label-mounted = %mountpoint%: %percentage_used%%
label-unmounted = 
label-warn = %mountpoint%: WARNING %percentage_free%% (%free%) remaining
label-warn-foreground = ${colors.alert}


[module/memory]
type = internal/memory
interval = 3
warn-percentage = 95

format =  <label> <ramp-used>
format-foreground = ${colors.primary}
label = %percentage_used%%
label-foreground = ${colors.foreground}

format-warn =  <label-warn> <ramp-used>
format-warn-foreground = ${colors.primary}
label-warn = RAM WARNING %percentage_used%%
label-warn-foreground = ${colors.alert}

; Only applies if <ramp-used> is used
ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █


[module/tray]
type = internal/tray
tray-spacing = 15px


[module/title]
type = internal/xwindow
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 4

; Available tokens:
;   %title%
;   %instance% (first part of the WM_CLASS atom, new in version 3.7.0)
;   %class%    (second part of the WM_CLASS atom, new in version 3.7.0)
; Default: %title%
label = %title% 
label-maxlen = 50


[module/network]
type = internal/network
interface-type = wireless
interval = 3.0

; Consider an `UNKNOWN` interface state as up.
; Some devices like USB network adapters have 
; an unknown state, even when they're running
unknown-as-up = true

; All labels support the following tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %netspeed%  [wireless+wired] (%upspeed% + %downspeed%) (New in version 3.6.0)
;   %linkspeed% [wired]
;   %mac%       [wireless+wired] (New in version 3.6.0)
format-connected = 󰖩 <label-connected>
format-connected-foreground = ${colors.primary}
label-connected = %signal%%
label-connected-foreground = ${colors.foreground}

format-disconnected = 󱚼 <label-disconnected>
format-disconnected-foreground = ${colors.alert}
label-disconnected = not connected
label-disconnected-foreground = ${colors.foreground}









































































[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}






[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}


[settings]
screenchange-reload = true
pseudo-transparency = true

