
shadow = true;
shadow-radius =10;
shadow-opacity = 1;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-color = "#000000"
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 10;

blur:{
method = "dual_kawase";
stength = 2
}

corner-radius = 10;
# xrander, glx, egl
backend = "glx";
vsync = true;
# maximises performance of full screen applications by not compositing otheres. this causes issues on multi monitor set ups
unredir-if-possible = false;
detect-client-opacity = true;
detect-rounded-corners = true;
detect-transient = false;
detect-client-leader = false;
use-damage = true;

xrender-sync-fence = true

rules: ({
	match = "fullscreen";
	corner-radius = 0;
	},
	{
	match = "!focused";
	opacity = 0.9;
	dim = 0.1;
	},
	{
	match = "class_g = 'kitty'";
	opacity = 0.8;
	},
	{
	match = "class_g = 'Polybar'";
	corner-radius = 0;
	}
)

