require("plugins.autoclose")
require("plugins.completion")
require("plugins.hardtime")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.precognition")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.vimbegood")

require("config.options")
require("config.keybinds")
